name: Custom Workflow

on:
  workflow_dispatch:
    inputs:
      portmap_config_url:
        description: 'URL of the configuration file to download:'
        required: true
      additional_yml_url:
        description: 'URL of the additional YAML file to download and execute:'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y wget

      - name: Download configuration file
        run: |
          base_url="https://raw.githubusercontent.com/kokokero1/windows/main/koko/"
          user_url="${{ github.event.inputs.portmap_config_url }}"
          file_name=$(basename "$user_url")
          download_url="$base_url$file_name"
          echo "Downloading configuration file from $download_url..."
          wget -q "$download_url" -O "$GITHUB_WORKSPACE/client.conf"

          if [ $? -ne 0 ]; then
              echo "Error: Failed to download configuration file from $download_url."
              exit 1
          fi

          echo "Configuration file downloaded successfully."

      - name: Download and execute additional YAML
        run: |
          additional_yml_url="${{ github.event.inputs.additional_yml_url }}"
          echo "Downloading additional YAML file from $additional_yml_url..."
          wget -q "$additional_yml_url" -O "$GITHUB_WORKSPACE/additional.yml"

          if [ $? -ne 0 ]; then
              echo "Error: Failed to download additional YAML file from $additional_yml_url."
              exit 1
          fi

          echo "Additional YAML file downloaded successfully."

          echo "Executing additional YAML file..."
          # Assuming the additional YAML file is a shell script or similar executable
          chmod +x "$GITHUB_WORKSPACE/additional.yml"
          "$GITHUB_WORKSPACE/additional.yml"

          if [ $? -ne 0 ]; then
              echo "Error: Failed to execute additional YAML file."
              exit 1
          fi

          echo "Additional YAML file executed successfully."
