name: Android Kero RDP

on:
  workflow_dispatch:
    inputs:
      portmap_config_url:
        description: 'Please paste the URL of the webpage or file you want to download:'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt-get install -y ruby wget unzip figlet python3-pip alsa-utils pulseaudio
          wget https://github.com/busyloop/lolcat/archive/master.zip
          unzip master.zip
          cd lolcat-master/bin/
          sudo gem install lolcat
          pip3 install git+https://github.com/tehmaze/lolcat.git
          sudo apt update
          sudo apt install -y openvpn novnc qemu-kvm websockify figlet

          # Initialize ALSA
          sudo alsactl init

      - name: Download configuration
        run: |
          user_url="${{ github.event.inputs.portmap_config_url }}"
          echo "Downloading content from $user_url..."
          wget -q "$user_url" -O "$GITHUB_WORKSPACE/client.conf"

          if [ $? -ne 0 ]; then
              echo "Error: Failed to download content from $user_url."
              exit 1
          fi

          sudo mv "$GITHUB_WORKSPACE/client.conf" "/etc/openvpn/client.conf"
          echo "Configuration saved."

      - name: Run Docker container with NoVNC
        run: |
          docker volume create --name my_volume
          docker run -d \
            --device /dev/kvm \
            -e RAM=10 \
            -p 6080:6080 \
            -p 5900:5900 \
            -e EMULATOR_DEVICE="Nexus 7" \
            -e WEB_VNC=true \
            --name Kero-Android9 \
            budtmo/docker-android:emulator_9.0

          nohup sudo websockify --web /usr/share/novnc 4000 localhost:5900 &

      - name: Start OpenVPN
        run: |
          sleep 10
          sudo openvpn --config /etc/openvpn/client.conf | lolcat -f
