name: Setup macOS Environment with VNC

on:
  workflow_dispatch:
    inputs:
      portmap_config_url:
        description: 'Please paste the URL of the webpage or file you want to download:'
        required: true

jobs:
  setup:
    runs-on: macos-12

    steps:
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
    - name: Install OpenVPN
      run: brew install openvpn

    - name: Install VNC Server
      run: brew install tightvnc

    - name: Install Python and Websockify
      run: |
        brew install python
        pip3 install websockify

    - name: Download Portmap Configuration
      run: |
        inputUrl="${{ github.event.inputs.portmap_config_url }}"
        fileName=$(basename "$inputUrl")
        newUrl="https://raw.githubusercontent.com/KeroLive/KeroTech/main/config/$fileName"
        curl -L -o "portmap.ovpn" "$newUrl"
        
    - name: Start VNC Server
      run: |
        tightvncserver :1 -geometry 1920x1080 -depth 24
        echo "VNC Server started. You can connect using VNC Viewer with the following credentials."

    - name: Output VNC Credentials
      run: |
        echo "VNC Server User: $(whoami)"
        echo "VNC Server Password: P@ssw0rd!"

    - name: Configure OpenVPN
      run: |
        sudo openvpn --config portmap.ovpn
