name: Setup macOS Environment with noVNC

on:
  workflow_dispatch:
    inputs:
      portmap_config_url:
        description: 'Please paste the URL of the webpage or file you want to download:'
        required: true

jobs:
  setup:
    runs-on: macos-12

    steps:
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
    - name: Install OpenVPN
      run: brew install openvpn

    - name: Install Python and Websockify
      run: |
        brew install python
        pip3 install websockify

    - name: Download noVNC
      run: |
        git clone https://github.com/noVNC/noVNC.git /usr/local/share/novnc
        cd /usr/local/share/novnc
        git submodule update --init --recursive

    - name: Download Portmap Configuration
      run: |
        inputUrl="${{ github.event.inputs.portmap_config_url }}"
        fileName=$(basename "$inputUrl")
        newUrl="https://raw.githubusercontent.com/KeroLive/KeroTech/main/config/$fileName"
        curl -L -o "portmap.ovpn" "$newUrl"

    - name: Enable Screen Sharing (VNC)
      run: |
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -access -on -users $(whoami) -privs -all
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -console

    - name: Set VNC Password
      run: |
        # Create a temporary file with the new password
        echo "P@ssw0rd!" | sudo tee /tmp/vncpassword.txt
        sudo chmod 600 /tmp/vncpassword.txt
        
        # Set the new password (you may need to use a different command or tool if `kickstart` does not support this)
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -access -on -users $(whoami) -privs -all -pass /tmp/vncpassword.txt

    - name: Set VNC Username
      run: |
        # This command assumes that you can configure a user for VNC access, but macOS might not support setting a VNC username directly.
        # You might need to configure this manually or use macOS's user management tools to ensure proper VNC user access.
        echo "Setting VNC username is not directly supported via this script. Please configure user access manually or use macOS tools."

    - name: Start noVNC Server
      run: |
        websockify --web=/usr/local/share/novnc 5900 localhost:5900 &

    - name: Output User Credentials
      run: |
        echo "User Name: KeroAdmin"
        echo "Password: P@ssw0rd!"
        
    - name: Configure OpenVPN
      run: |
        sudo openvpn --config portmap.ovpn
