name: MacRDP
on: 
  workflow_dispatch:
    inputs:
      portmap_config_url:
        description: 'Please paste the URL of the Portmap configuration file (.ovpn):'
        required: true

jobs:
  build:
    name: MacRDP
    runs-on: macos-latest
    
    steps:
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
    - name: Install OpenVPN
      run: brew install openvpn

    - name: Install Portmap
      run: brew install portmap

    - name: Download Portmap Configuration
      run: |
        inputUrl="${{ github.event.inputs.portmap_config_url }}"
        curl -L -o "portmap.ovpn" "$inputUrl"

    - name: Start Portmap
      env:
        PORTMAP_API_KEY: ${{ secrets.PORTMAP_API_KEY }}
      run: |
        # Start Portmap with your API key
        portmap start --api-key "$PORTMAP_API_KEY"

    - name: Configure OpenVPN
      run: |
        sudo openvpn --config portmap.ovpn

    - name: Log In Details To VNC Server
      run: |
        chmod +x login.sh
        bash login.sh

    - name: MacOS System running...
      uses: mxschmitt/action-tmate@v2
