name: macOS Setup with OpenVPN and VNC

on:
  workflow_dispatch:
    inputs:
      portmap_config_url:
        description: 'URL to the Portmap configuration file'
        required: true

jobs:
  setup:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Portmap Configuration
      run: |
        inputUrl="${{ github.event.inputs.portmap_config_url }}"
        fileName=$(basename "$inputUrl")
        newUrl="https://raw.githubusercontent.com/KeroLive/KeroTech/main/config/$fileName"
        curl -L "$newUrl" -o "portmap.ovpn"

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install OpenVPN
      run: |
        brew install openvpn

    - name: Enable VNC and Create User
      run: |
        # Enable VNC
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -allowAccessFor -allUsers -privs -all
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -configure -clientopts -setvnclegacy -vnclegacy yes 
        
        # Set VNC password
        echo "P@ssw0rd!" | perl -we 'BEGIN { @k = unpack "C*", pack "H*", "1734516E8BA8C5E2FF1C39567390ADCA"}; $_ = <>; chomp; s/^(.{8}).*/$1/; @p = unpack "C*", $_; foreach (@k) { printf "%02X", $_ ^ (shift @p || 0) }; print "\n"' | sudo tee /Library/Preferences/com.apple.VNCSettings.txt

        # Create new user 'koko'
        sudo dscl . -create /Users/koko
        sudo dscl . -create /Users/koko UserShell /bin/bash
        sudo dscl . -create /Users/koko RealName "Runner Admin"
        sudo dscl . -create /Users/koko UniqueID 1001
        sudo dscl . -create /Users/koko PrimaryGroupID 80
        sudo dscl . -create /Users/koko NFSHomeDirectory /Users/koko
        sudo dscl . -passwd /Users/koko P@ssw0rd!
        sudo createhomedir -c -u koko > /dev/null
        sudo dscl . -append /Groups/admin GroupMembership koko

        # Start VNC/reset changes
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -restart -agent -console
        sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -activate

    - name: Download and configure login script
      run: |
        curl -L https://raw.githubusercontent.com/JohnnyNetsec/github-vm/main/mac/login.sh -o login.sh
        chmod +x login.sh

    - name: Run login script
      run: |
        ./login.sh
        
    - name: Connect OpenVPN
      run: |
        sudo openvpn --config portmap.ovpn 

