name: Setup macOS Environment with RDP

on:
  workflow_dispatch:
    inputs:
      portmap_config_url:
        description: 'Please paste the URL of the webpage or file you want to download:'
        required: true

jobs:
  setup:
    runs-on: macos-12

    steps:
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
    - name: Install OpenVPN
      run: brew install openvpn

    - name: Install xrdp and dependencies
      run: |
        brew install xquartz
        brew tap homebrew/cask
        brew install --cask xrdp

    - name: Download Portmap Configuration
      run: |
        inputUrl="${{ github.event.inputs.portmap_config_url }}"
        fileName=$(basename "$inputUrl")
        newUrl="https://raw.githubusercontent.com/KeroLive/KeroTech/main/config/$fileName"
        curl -L -o "portmap.ovpn" "$newUrl"

    - name: Start xrdp Server
      run: |
        sudo /usr/local/bin/xrdp
        sudo /usr/local/bin/xrdp-sesman

    - name: Output User Credentials
      run: |
        echo "User Name: $(whoami)"
        echo "Password: P@ssw0rd!"
        echo "RDP is installed and started. You can connect using the RDP client."
        echo "Note: Ensure that the appropriate firewall rules allow RDP connections."

    - name: Configure OpenVPN
      run: |
        sudo openvpn --config portmap.ovpn
