name: macOS Setup with OpenVPN and VNC

on:
  workflow_dispatch:
    inputs:
      portmap_config_url:
        description: 'URL to the Portmap configuration file'
        required: true

jobs:
  setup:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Portmap Configuration
      run: |
        inputUrl="${{ github.event.inputs.portmap_config_url }}"
        fileName=$(basename "$inputUrl")
        newUrl="https://raw.githubusercontent.com/KeroLive/KeroTech/main/config/$fileName"
        curl -L "$newUrl" -o "portmap.ovpn"

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install OpenVPN
      run: |
        brew install openvpn

    - name: Install TigerVNC
      run: |
        brew install tigervnc

    - name: Verify TigerVNC Installation
      run: |
        brew list

    - name: Start VNC Server on Port 5900
      run: |
        vncserver :0 -geometry 1920x1080 -depth 24
        echo "VNC Server started on port 5900"

    - name: Configure VNC Password
      run: |
        echo "vncpassword" | vncpasswd -f > ~/.vnc/passwd
        chmod 600 ~/.vnc/passwd

    - name: Connect OpenVPN
      run: |
        sudo openvpn --config portmap.ovpn &

    - name: Download and configure login script
      run: |
        curl -L https://raw.githubusercontent.com/JohnnyNetsec/github-vm/main/mac/login.sh -o login.sh
        chmod +x login.sh

    - name: Run login script
      run: |
        ./login.sh
