name: Kero RDP

on:
  workflow_dispatch:
    inputs:
      portmap_config_url:
        description: 'Please paste the URL of the webpage or file you want to download:'
        required: true

jobs:
  build:
    runs-on: macos-12

    steps:
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
    - name: Install OpenVPN
      run: brew install openvpn
      
    - name: Download Portmap Configuration
      run: |
        inputUrl="${{ github.event.inputs.portmap_config_url }}"
        fileName=$(basename "$inputUrl")
        newUrl="https://raw.githubusercontent.com/KeroLive/KeroTech/main/config/$fileName"
        curl -L -o "portmap.ovpn" "$newUrl"
        
    - name: Enable Remote Desktop (SSH)
      run: sudo systemsetup -setremotelogin on
      
    - name: Configure Firewall for OpenVPN
      run: sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/local/bin/openvpn
    
    - name: Create Local Users
      run: |
        sudo dscl . -create /Users/KeroAdmin
        sudo dscl . -create /Users/KeroAdmin UserShell /bin/bash
        sudo dscl . -create /Users/KeroAdmin RealName "Kero Admin"
        sudo dscl . -create /Users/KeroAdmin UniqueID "510"
        sudo dscl . -create /Users/KeroAdmin PrimaryGroupID 20
        sudo dscl . -create /Users/KeroAdmin NFSHomeDirectory /Users/KeroAdmin
        sudo dscl . -passwd /Users/KeroAdmin "P@ssw0rd!"
        sudo dscl . -append /Groups/admin GroupMembership KeroAdmin

        sudo dscl . -create /Users/Kero
        sudo dscl . -create /Users/Kero UserShell /bin/bash
        sudo dscl . -create /Users/Kero RealName "Kero"
        sudo dscl . -create /Users/Kero UniqueID "511"
        sudo dscl . -create /Users/Kero PrimaryGroupID 20
        sudo dscl . -create /Users/Kero NFSHomeDirectory /Users/Kero
        sudo dscl . -passwd /Users/Kero "P@ssw0rd!"
        sudo dscl . -append /Groups/admin GroupMembership Kero

    - name: Configure OpenVPN
      run: sudo openvpn --config portmap.ovpn --daemon
      
    - name: Output User Credentials
      run: |
        echo "User Name: KeroAdmin"
        echo "Password: P@ssw0rd!"
