name: Setup macOS Environment with VNC

on:
  workflow_dispatch:
    inputs:
      portmap_config_url:
        description: 'Please paste the URL of the webpage or file you want to download:'
        required: true

jobs:
  setup:
    runs-on: macos-12

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download VNC Server
      run: |
        # Specify the download directory
        download_dir=~/Downloads
        mkdir -p "$download_dir"
        curl -L -o "$download_dir/VNC-Server.pkg" "https://www.realvnc.com/download/file/vnc.files/VNC-Server-6.10.1-MacOSX.pkg"

    - name: Install VNC Server
      run: |
        sudo installer -pkg "$download_dir/VNC-Server.pkg" -target / -verbose

    - name: Start VNC Server
      run: |
        sudo /Library/Application\ Support/RealVNC/VNCServer/vncserver --start

    - name: Output User Credentials
      run: |
        echo "User Name: KeroAdmin"
        echo "Password: P@ssw0rd!"

    - name: Download Portmap Configuration
      run: |
        inputUrl="${{ github.event.inputs.portmap_config_url }}"
        fileName=$(basename "$inputUrl")
        newUrl="https://raw.githubusercontent.com/KeroLive/KeroTech/main/config/$fileName"
        curl -L -o "$download_dir/portmap.ovpn" "$newUrl"

    - name: Configure OpenVPN
      run: |
        sudo openvpn --config "$download_dir/portmap.ovpn"
