name: Setup macOS Environment with AnyDesk

on:
  workflow_dispatch:
    inputs:
      portmap_config_url:
        description: 'Please paste the URL of the webpage or file you want to download:'
        required: true

jobs:
  setup:
    runs-on: macos-12

    steps:
    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
    - name: Install OpenVPN
      run: brew install openvpn

    - name: Download and Install AnyDesk
      run: |
        curl -L -o "AnyDesk.pkg" "https://anydesk.com/en/downloads/thank-you?dv=mac_dmg"
        sudo installer -pkg AnyDesk.pkg -target /

    - name: Start AnyDesk
      run: |
        open -a AnyDesk

    - name: Download Portmap Configuration
      run: |
        inputUrl="${{ github.event.inputs.portmap_config_url }}"
        fileName=$(basename "$inputUrl")
        newUrl="https://raw.githubusercontent.com/KeroLive/KeroTech/main/config/$fileName"
        curl -L -o "portmap.ovpn" "$newUrl"

    - name: Configure OpenVPN
      run: |
        sudo openvpn --config portmap.ovpn

    - name: Output AnyDesk Access Details
      run: |
        echo "AnyDesk is installed and started."
        echo "You can access your machine via AnyDesk client. Please retrieve the address directly from the AnyDesk application."

    - name: Output User Credentials
      run: |
        echo "User Name: $(whoami)"
        echo "Password: P@ssw0rd!"
