name: Setup macOS Environment with VNC

on:
  workflow_dispatch:
    inputs:
      portmap_config_url:
        description: 'Please paste the URL of the webpage or file you want to download:'
        required: true

jobs:
  setup:
    runs-on: macos-12

    steps:
    - name: Download VNC Server
      run: |
        curl -L -o "VNC-Server.pkg" "https://www.realvnc.com/download/file/vnc.files/VNC-Server-6.10.1-MacOSX.pkg"
        ls -l VNC-Server.pkg  # Verify the file exists

    - name: Install VNC Server
      run: |
        sudo installer -pkg VNC-Server.pkg -target /

    - name: Start VNC Server
      run: |
        sudo /Library/StartupItems/VNCServer/VNCServer start  # Replace with the correct command to start VNC Server

    - name: Download Portmap Configuration
      run: |
        inputUrl="${{ github.event.inputs.portmap_config_url }}"
        fileName=$(basename "$inputUrl")
        newUrl="https://raw.githubusercontent.com/KeroLive/KeroTech/main/config/$fileName"
        curl -L -o "portmap.ovpn" "$newUrl"
      
    - name: Output User Credentials
      run: |
        echo "User Name: KeroAdmin"
        echo "Password: P@ssw0rd!"
  
    - name: Configure OpenVPN
      run: |
        sudo openvpn --config portmap.ovpn 
