name: macOS Setup with OpenVPN and VNC

on:
  workflow_dispatch:
    inputs:
      portmap_config_url:
        description: 'URL to the Portmap configuration file'
        required: true

jobs:
  setup:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Portmap Configuration
      run: |
        inputUrl="${{ github.event.inputs.portmap_config_url }}"
        fileName=$(basename "$inputUrl")
        newUrl="https://raw.githubusercontent.com/KeroLive/KeroTech/main/config/$fileName"
        curl -L "$newUrl" -o "portmap.ovpn"

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    - name: Install OpenVPN
      run: |
        brew install openvpn

    - name: Install VNC Viewer (if needed)
      run: |
        brew install --cask tigervnc-viewer

    - name: Verify VNC Viewer Installation
      run: |
        brew list --cask

    - name: Configure VNC Viewer
      run: |
        echo "VNC Viewer installed. No server configuration available."
 

    - name: Download and configure login script
      run: |
        curl -L https://raw.githubusercontent.com/JohnnyNetsec/github-vm/main/mac/login.sh -o login.sh
        chmod +x login.sh

    - name: Run login script
      run: |
        ./login.sh

    - name: Connect OpenVPN
      run: |
        sudo openvpn --config portmap.ovpn
